name: Verify Pull Request

on:
  pull_request:
    branches:
      - main

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  BUN_ENV: development

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Run
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun.js
        uses: ./.github/actions/bun

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   with:
      #     job: ${{ github.job }}
      #   if: failure()

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restoring Bun.js
        uses: ./.github/actions/bun

      - name: Lint Code
        run: bun run lint
        env:
          CI: true

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   with:
      #     job: ${{ github.job }}
      #   if: failure()

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restoring Bun.js
        uses: ./.github/actions/bun

      - name: Build All
        run: bun run build
        env:
          CI: true

      # - name: Slack Error Notification
      #   uses: ./.github/actions/slack-error
      #   with:
      #     job: ${{ github.job }}
      #   if: failure()

      # - name: Slack Success Notification
      #   uses: ./.github/actions/slack-success
      #   with:
      #     job: ${{ github.job }}
      #   if: success()
